name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ucp-angular-client/package-lock.json
        
    - name: Install dependencies
      run: cd ucp-angular-client && npm ci
      
    - name: Run tests
      run: cd ucp-angular-client && npm test -- --watch=false
      
    - name: Build
      run: cd ucp-angular-client && npm run build
